WavFrontend:
  cmvn_file: ./model_repo_paraformer_large_offline/feature_extractor/am.mvn
  frontend_conf:
    fs: 16000
    window: hamming
    n_mels: 80
    frame_length: 25
    frame_shift: 10
    lfr_m: 7
    lfr_n: 6
    filter_length_max: -.inf